#-------------------------------
# General Site Settings

title: Vignesh Kumaresan | Innovation Engineer
description: Per Aspera Ad Astra # this means to ignore newlines until "baseurl:"
baseurl: "/galada" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Vignesh Kumaresan
author-avatar: avatar.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/vigneshesan # Add your Facebook handle
twitter:   https://twitter.com/vigneshesan # Add your Facebook handle
instagram: https://www.instagram.com/vigneshesan # Add your Facebook handle
github: https://www.github.com/vigneshesan # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-172431519-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: vigneshk.us10.list-manage.com/subscribe/post?u=f3ef763b1743878019a50d991&amp;id=36912fa33e # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
